name: sync kubeadm command

on:
  push:
    branches:
      - "*"

env:
  GO_VERSION: '1.25.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: sync kubeadm command
        run: go run cmd/builder/main.go sync-kubeadm --kubernetes-version v1.31.7 --configFile builder.yaml --github-owner ${{ secrets.OWNER }} --github-repo ${{ secrets.REPO }}  --github-token ${{ secrets.TOKEN }}
